Repository Thunderrock424242/Wilderness-Odyssey-API, pull requests merged in 2025-08, with the labels that each got.

#48 Persist donation and server ad opt-outs across versions
  src/main/java/com/thunder/wildernessodysseyapi/Core/WildernessOdysseyAPIMainModClass.java
  src/main/java/com/thunder/wildernessodysseyapi/ModPackPatches/server/PartnerAdHandler.java
  src/main/java/com/thunder/wildernessodysseyapi/donations/DonationReminder.java
  src/main/java/com/thunder/wildernessodysseyapi/donations/command/DonationOptOutCommand.java
  src/main/java/com/thunder/wildernessodysseyapi/donations/config/DonationReminderConfig.java
Labels: codex

#49 Fix cryo tube block rendering and spawn hookup
  src/main/java/com/thunder/wildernessodysseyapi/Client/CryoTubeRenderSetup.java
  src/main/java/com/thunder/wildernessodysseyapi/WorldGen/BunkerStructure/SpawnBlock/WorldSpawnHandler.java
  src/main/resources/assets/wildernessodysseyapi/blockstates/cryo_tube_block.json
  src/main/resources/assets/wildernessodysseyapi/item/cryo_tube_block.json
  src/main/resources/assets/wildernessodysseyapi/models/block/cryo_tube_block.json
Labels: codex

#55 Add dedicated terrain replacer block
  src/main/java/com/thunder/wildernessodysseyapi/Core/WildernessOdysseyAPIMainModClass.java
  src/main/java/com/thunder/wildernessodysseyapi/WorldGen/BunkerStructure/TerrainBlockReplacer.java
  src/main/java/com/thunder/wildernessodysseyapi/WorldGen/BunkerStructure/Worldedit/WorldEditStructurePlacer.java
  src/main/java/com/thunder/wildernessodysseyapi/WorldGen/blocks/TerrainReplacerBlock.java
Labels: codex

#56 Add facing blockstate for cryo tube
  src/main/resources/assets/wildernessodysseyapi/blockstates/cryo_tube_block.json
Labels: codex

#57 Fix cryo tube asset naming
  src/main/java/com/thunder/wildernessodysseyapi/WorldGen/blocks/CryoTubeBlock.java
  src/main/resources/assets/wildernessodysseyapi/blockstates/Cryo_tube.json
  src/main/resources/assets/wildernessodysseyapi/blockstates/cryo_tube.json
  src/main/resources/assets/wildernessodysseyapi/item/cryo_tube_block.json
  src/main/resources/assets/wildernessodysseyapi/lang/en_us.json
  src/main/resources/assets/wildernessodysseyapi/models/block/cryo_tube.json
  src/main/resources/assets/wildernessodysseyapi/models/block/cryo_tube.mtl
  src/main/resources/assets/wildernessodysseyapi/models/block/cryo_tube.obj
  src/main/resources/assets/wildernessodysseyapi/models/item/cryo_tube.json
  src/main/resources/assets/wildernessodysseyapi/textures/block/cryo_tube.png
Labels: codex

#60 Avoid duplicate bunker structure placement
  src/main/java/com/thunder/wildernessodysseyapi/WorldGen/BunkerStructure/Worldedit/WorldEditStructurePlacer.java
Labels: codex

#64 fix: guard WorldEdit structure placement before init
  src/main/java/com/thunder/wildernessodysseyapi/Core/WildernessOdysseyAPIMainModClass.java
  src/main/java/com/thunder/wildernessodysseyapi/WorldGen/BunkerStructure/Worldedit/WorldEditStructurePlacer.java
Labels: codex

#65 feat: separate conflict logging
  src/main/java/com/thunder/wildernessodysseyapi/Core/WildernessOdysseyAPIMainModClass.java
  src/main/java/com/thunder/wildernessodysseyapi/ModConflictChecker/RegistryConflictHandler.java
  src/main/java/com/thunder/wildernessodysseyapi/ModConflictChecker/ShaderConflictChecker.java
  src/main/java/com/thunder/wildernessodysseyapi/ModConflictChecker/Util/LoggerUtil.java
  src/main/java/com/thunder/wildernessodysseyapi/ModConflictChecker/Util/Utils.java
Labels: codex

#68 fix: defer worldedit block type access
  src/main/java/com/thunder/wildernessodysseyapi/Core/WildernessOdysseyAPIMainModClass.java
Labels: codex

#74 Run CodeQL for Java and GitHub Actions
  .github/workflows/codeql.yml
  qodana.yaml
Labels: codex

#76 feat: extend API for compatibility and structure utilities
  APIchangelog.txt
  src/main/java/com/thunder/wildernessodysseyapi/compat/ModCompatUtil.java
  src/main/java/com/thunder/wildernessodysseyapi/util/LightweightMath.java
  src/main/java/com/thunder/wildernessodysseyapi/worldgen/jigsaw/CustomJigsawManager.java
  src/main/java/com/thunder/wildernessodysseyapi/worldgen/structure/StructureUtils.java
Labels: codex

#78 Adds World Versioning System.- bugfix 2
  src/main/java/com/thunder/wildernessodysseyapi/ModPackPatches/client/WorldVersionChecker.java
Labels: enhancement

#81 Require cryo tube in bunker schematics
  src/main/java/com/thunder/wildernessodysseyapi/WorldGen/BunkerStructure/BunkerStructureGenerator.java
  src/main/java/com/thunder/wildernessodysseyapi/WorldGen/BunkerStructure/Features/BunkerFeature.java
  src/main/java/com/thunder/wildernessodysseyapi/WorldGen/BunkerStructure/StructureSpawnTracker.java
  src/main/java/com/thunder/wildernessodysseyapi/WorldGen/BunkerStructure/Worldedit/WorldEditStructurePlacer.java
  src/main/java/com/thunder/wildernessodysseyapi/WorldGen/worldgen/structures/MeteorStructureSpawner.java
Labels: codex

#80 Add pack metadata for resources
  src/main/resources/pack.mcmeta
Labels: codex

#79 Ensure doors close when locked and timer sticks glow
  src/main/java/com/thunder/wildernessodysseyapi/command/DoorLockCommand.java
  src/main/java/com/thunder/wildernessodysseyapi/doorlock/DoorLockEvents.java
Labels: codex

#84 Add cryo tube sleep limit and waking API
  src/main/java/com/thunder/wildernessodysseyapi/WorldGen/blocks/CryoTubeBlock.java
  src/main/java/com/thunder/wildernessodysseyapi/api/CryoSleepAPI.java
  src/main/java/com/thunder/wildernessodysseyapi/api/CryoSleepEvent.java
  src/main/resources/assets/wildernessodysseyapi/lang/en_us.json
Labels: codex

#85 Fix cryo tube placement and bounding box
  src/main/java/com/thunder/wildernessodysseyapi/WorldGen/blocks/CryoTubeBlock.java
  src/main/java/com/thunder/wildernessodysseyapi/WorldGen/blocks/CryoTubeBlockItem.java
Labels: codex

#86 Skip spawn adjustments in Peaceful difficulty
  src/main/java/com/thunder/wildernessodysseyapi/MobControl/MobSpawnAdjuster.java
Labels: codex

#88 Add destructive sky torch beam effect
  src/main/java/com/thunder/wildernessodysseyapi/Core/WildernessOdysseyAPIMainModClass.java
  src/main/java/com/thunder/wildernessodysseyapi/item/ModItems.java
  src/main/java/com/thunder/wildernessodysseyapi/item/SkyTorchStaffItem.java
  src/main/resources/assets/wildernessodysseyapi/lang/en_us.json
  src/main/resources/assets/wildernessodysseyapi/models/item/sky_torch_staff.json
Labels: codex

#90 Add custom creative tab with amethyst icon
  src/main/java/com/thunder/wildernessodysseyapi/Core/WildernessOdysseyAPIMainModClass.java
  src/main/java/com/thunder/wildernessodysseyapi/item/ModCreativeTabs.java
  src/main/resources/assets/wildernessodysseyapi/lang/en_us.json
Labels: codex

#89 Render translucent hint for cloaked entities
  src/main/java/com/thunder/wildernessodysseyapi/Client/CloakRenderHandler.java
  src/main/java/com/thunder/wildernessodysseyapi/item/CloakItem.java
  src/main/java/com/thunder/wildernessodysseyapi/item/ModItems.java
  src/main/java/com/thunder/wildernessodysseyapi/mixin/CloakRenderMixin.java
  src/main/resources/assets/wildernessodysseyapi/lang/en_us.json
  src/main/resources/assets/wildernessodysseyapi/models/item/cloak_item.json
  src/main/resources/mixins.wildernessodysseyapi.json
Labels: codex

#91 Add destructive sky torch beam effect
  changelog.txt
  src/main/java/com/thunder/wildernessodysseyapi/Core/WildernessOdysseyAPIMainModClass.java
  src/main/java/com/thunder/wildernessodysseyapi/skytorch/SkyTorchItems.java
  src/main/java/com/thunder/wildernessodysseyapi/skytorch/SkyTorchStaffItem.java
Labels: codex

#92 Fix compilation errors
  src/main/java/com/thunder/wildernessodysseyapi/Core/WildernessOdysseyAPIMainModClass.java
  src/main/java/com/thunder/wildernessodysseyapi/skytorch/SkyTorchStaffItem.java
Labels: codex

#94 Add memory allocation advisor and peak usage tracker
  src/main/java/com/thunder/wildernessodysseyapi/MemUtils/MemCheckCommand.java
  src/main/java/com/thunder/wildernessodysseyapi/MemUtils/MemoryTracker.java
  src/main/java/com/thunder/wildernessodysseyapi/MemUtils/MemoryTrackerClient.java
  src/main/java/com/thunder/wildernessodysseyapi/MemUtils/MemoryUtils.java
Labels: codex

#95 Optimize campfire effects and reduce log spam
  src/main/java/com/thunder/wildernessodysseyapi/MemUtils/MemoryUtils.java
  src/main/java/com/thunder/wildernessodysseyapi/WorldGen/BunkerStructure/SpawnBlock/WorldSpawnHandler.java
  src/main/java/com/thunder/wildernessodysseyapi/WorldGen/BunkerStructure/TerrainBlockReplacer.java
  src/main/java/com/thunder/wildernessodysseyapi/WorldGen/BunkerStructure/Worldedit/WorldEditStructurePlacer.java
  src/main/java/com/thunder/wildernessodysseyapi/mixin/CampfireBlockMixin.java
Labels: codex

#96 Throttle spawn block search
  src/main/java/com/thunder/wildernessodysseyapi/MemUtils/MemoryTracker.java
  src/main/java/com/thunder/wildernessodysseyapi/MemUtils/MemoryTrackerClient.java
  src/main/java/com/thunder/wildernessodysseyapi/MemUtils/MemoryUtils.java
  src/main/java/com/thunder/wildernessodysseyapi/WorldGen/BunkerStructure/SpawnBlock/PlayerSpawnHandler.java
  src/main/java/com/thunder/wildernessodysseyapi/WorldGen/BunkerStructure/SpawnBlock/WorldSpawnHandler.java
Labels: codex

#100 Fix memory utils compilation issues
  src/main/java/com/thunder/wildernessodysseyapi/MemUtils/MemoryUtils.java
Labels: codex

#99 Reduce tick overhead
  src/main/java/com/thunder/wildernessodysseyapi/Core/WildernessOdysseyAPIMainModClass.java
  src/main/java/com/thunder/wildernessodysseyapi/MemUtils/MemoryTracker.java
  src/main/java/com/thunder/wildernessodysseyapi/MemUtils/MemoryTrackerClient.java
  src/main/java/com/thunder/wildernessodysseyapi/MemUtils/MemoryUtils.java
  src/main/java/com/thunder/wildernessodysseyapi/ModPackPatches/ClientSaveHandler.java
  src/main/java/com/thunder/wildernessodysseyapi/WorldGen/BunkerStructure/SpawnBlock/PlayerSpawnHandler.java
  src/main/java/com/thunder/wildernessodysseyapi/WorldGen/BunkerStructure/SpawnBlock/WorldSpawnHandler.java
Labels: codex

#102 Move spawn debug logs to trace
  src/main/java/com/thunder/wildernessodysseyapi/MobControl/MobSpawnAdjuster.java
Labels: codex

#105 Add world generation scan command for diagnostics
  README.md
  src/main/java/com/thunder/wildernessodysseyapi/Core/WildernessOdysseyAPIMainModClass.java
  src/main/java/com/thunder/wildernessodysseyapi/command/WorldGenScanCommand.java
Labels: codex

#109 Run CodeQL on all branches
  .env.example
  .github/workflows/codeql-config.yml
  .github/workflows/codeql.yml
  .gitignore
  README.md
Labels: codex

#110 Improve worldgenscan command output
  src/main/java/com/thunder/wildernessodysseyapi/command/WorldGenScanCommand.java
Labels: enhancement, codex

#112 Improve worldgenscan command output
  src/main/java/com/thunder/wildernessodysseyapi/command/WorldGenScanCommand.java
  src/main/java/com/thunder/wildernessodysseyapi/command/WorldGenScanViewer.java
Labels: codex

#111 feat: show structure info in swing window
  src/main/java/com/thunder/wildernessodysseyapi/command/StructureInfoCommand.java
Labels: codex
